### PR TITLE
Frame counter based keyframe calculation

### LINKED ISSUE #29: Framecounter for keyframe
@davedoesdev Do you think that a framecounter will be more useful in determining the keyframe? I can submit PR.

Because of the asynchronous nature of the video encoder and reader, the key frame interval is erratic if time functions are used as you posted in https://github.com/davedoesdev/webm-muxer.js/issues/26#issuecomment-1167692628

### PR DESCRIPTION
**Pull request by onthegit**
Frame counter based keyframe calculation. Closes https://github.com/davedoesdev/webm-muxer.js/issues/29

### CODE REVIEW

**Comment by onthegit** [comment]
I do not have camera to test the demo page,...

**Comment by davedoesdev** [comment]
@onthegit thanks this looks good.
If it's okay with you, I might add it as an alternative via a config option rather than replace the existing method.

**Comment by davedoesdev** [comment]
@onthegit I've adapted this in 375cc63f5bd940303037026347ff141b2ee2281f

What do you think?

Thanks again for the idea.

**Comment by onthegit** [comment]
@davedoesdev thanks.

**Comment by davedoesdev** [comment]
Something not quite right. It seems the framerate I actually get from the video frames is half what I ask for.
Will investigate and also check the Cues are what's expected.

**Comment by davedoesdev** [comment]
`MediaTrackSettings.frameRate` seems to reflect desired frame rate, not the actual one. From the timestamps I'm seeing 15 fps whereas `frameRate` reports 30.

**Comment by davedoesdev** [comment]
What I'm seeing on my machine (Linux) is the actual frame rate maxes out at 15fps even if I ask for more. But `frameRate` is reported as what I ask for regardless.

**Pull request closed without merging**
